export const FETCH_APP_DETAILS = 'FETCH_APP_DETAILS';
export const FETCH_APP_DETAILS_SUCCESS = 'FETCH_APP_DETAILS_SUCCESS';
export const FETCH_APP_DETAILS_FAILURE = 'FETCH_APP_DETAILS_FAILURE';
export const CLEAR_APP_DETAILS = 'CLEAR_APP_DETAILS';
