export const CREATE_DAPP = 'CREATE_DAPP';
export const CREATE_DAPP_SUCCESS = 'CREATE_DAPP_SUCCESS';
export const CREATE_DAPP_FAILURE = 'CREATE_DAPP_FAILURE';

export const CREATE_DAPP_SUBMIT_CLICKED = 'CREATE_DAPP_SUBMIT_CLICKED';
