export const RECORD_STAT = 'RECORD_STAT';
export const RECORD_STAT_SUCCESS = 'RECORD_STAT_SUCCESS';
export const RECORD_STAT_FAILURE = 'RECORD_STAT_FAILURE';

export const FETCH_STATS = 'FETCH_STATS';
export const CLEAR_STATS = 'CLEAR_STATS';
export const FETCH_STATS_SUCCESS = 'FETCH_STATS_SUCCESS';
export const FETCH_STATS_FAILURE = 'FETCH_STATS_FAILURE';
