export const FETCH_PRESALE_ITEMS = 'FETCH_PRESALE_ITEMS';
export const FETCH_PRESALE_ITEMS_SUCCESS = 'FETCH_PRESALE_ITEMS_SUCCESS';
export const FETCH_PRESALE_ITEMS_FAILURE = 'FETCH_PRESALE_ITEMS_FAILURE';

export const FETCH_ITEMS_IN_CART = 'FETCH_ITEMS_IN_CART';
export const FETCH_ITEMS_IN_CART_SUCCESS = 'FETCH_ITEMS_IN_CART_SUCCESS';
export const FETCH_ITEMS_IN_CART_FAILURE = 'FETCH_ITEMS_IN_CART_FAILURE';

export const UPDATE_QUANTITY_BY_ITEM_ID = 'UPDATE_QUANTITY_BY_ITEM_ID';
export const UPDATE_QUANTITY_BY_ITEM_ID_SUCCESS =
  'UPDATE_QUANTITY_BY_ITEM_ID_SUCCESS';
export const UPDATE_QUANTITY_BY_ITEM_ID_FAILURE =
  'UPDATE_QUANTITY_BY_ITEM_ID_FAILURE';

export const ADD_TO_REMOVE_LIST = 'ADD_TO_REMOVE_LIST';
export const ADD_TO_REMOVE_LIST_SUCCESS = 'ADD_TO_REMOVE_LIST_SUCCESS';
export const ADD_TO_REMOVE_LIST_FAILURE = 'ADD_TO_REMOVE_LIST_FAILURE';

export const ADD_ALL_TO_REMOVE_LIST = 'ADD_ALL_TO_REMOVE_LIST';
export const ADD_ALL_TO_REMOVE_LIST_SUCCESS = 'ADD_ALL_TO_REMOVE_LIST_SUCCESS';
export const ADD_ALL_TO_REMOVE_LIST_FAILURE = 'ADD_ALL_TO_REMOVE_LIST_FAILURE';

export const REMOVE_ALL_FROM_CART = 'REMOVE_ALL_FROM_CART';
export const REMOVE_ALL_FROM_CART_SUCCESS = 'REMOVE_ALL_FROM_CART_SUCCESS';
export const REMOVE_ALL_FROM_CART_FAILURE = 'REMOVE_ALL_FROM_CART_FAILURE';

export const ADD_ITEM_INTO_CART = 'ADD_ITEM_INTO_CART';
export const ADD_ITEM_INTO_CART_SUCCESS = 'ADD_ITEM_INTO_CART_SUCCESS';
export const ADD_ITEM_INTO_CART_FAILURE = 'ADD_ITEM_INTO_CART_FAILURE';

export const FETCH_CART_ITEMS = 'FETCH_CART_ITEMS';
export const FETCH_CART_ITEMS_SUCCESS = 'FETCH_CART_ITEMS_SUCCESS';
export const FETCH_CART_ITEMS_FAILURE = 'FETCH_CART_ITEMS_FAILURE';

export const ADD_TO_PAYPAL_TRANSACTION = 'ADD_TO_PAYPAL_TRANSACTION';
export const ADD_TO_PAYPAL_TRANSACTION_SUCCESS =
  'ADD_TO_PAYPAL_TRANSACTION_SUCCESS';
export const ADD_TO_PAYPAL_TRANSACTION_FAILURE =
  'CHECKOUTADD_TO_PAYPAL_TRANSACTION_FAILURE';

export const UPDATE_MY_VOUCHERS = 'UPDATE_MY_VOUCHERS';
export const UPDATE_MY_VOUCHERS_SUCCESS = 'UPDATE_MY_VOUCHERS_SUCCESS';
export const UPDATE_MY_VOUCHERS_FAILURE = 'UPDATE_MY_VOUCHERS_FAILURE';
