export const FETCH_APP_REVIEWS = 'FETCH_APP_REVIEWS';
export const FETCH_APP_REVIEWS_SUCCESS = 'FETCH_APP_REVIEWS_SUCCESS';
export const FETCH_APP_REVIEWS_FAILURE = 'FETCH_APP_REVIEWS_FAILURE';
export const CLEAR_APP_REVIEWS = 'CLEAR_APP_REVIEWS';

export const ADD_APP_REVIEW = 'ADD_APP_REVIEW';
export const ADD_APP_REVIEW_SUCCESS = 'ADD_APP_REVIEW_SUCCESS';
export const ADD_APP_REVIEW_FAILURE = 'ADD_APP_REVIEW_FAILURE';
